site_name: Christopher Seaman
site_url: https://badmath.org
theme: 
  name: material
  locale: en
  highlightjs: true
  hljs_languages:
    - sql
    - python
    - yaml
  font:
    text: Helvetical Neue
    code: Fira Mono
